language: c
compiler:
  - gcc
  - clang

before_install: ./.travis/prepare.sh

sudo: true

env:
  - KERNEL=3.17.7 DPDK=1
  - KERNEL=3.17.7 DPDK=1 OPTS="--enable-shared"

script: ./.travis/build.sh $OPTS
